=== jewelsjacobs/apiblueprints/alarm/includes/alarm-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "name": {
      "type": "string"
    },
    "metric": {
      "type": "string"
    },
    "plugin": {
      "type": ["string", "null"]
    },
    "triggerInterval": {
      "type": "integer"
    },
    "typeId": {
      "type": "integer"
    },
    "familyId": {
      "type": "integer"
    },
    "triggerPredicate": {
      "type": "object",
      "properties": {
        "agg": {
          "type": "string"
        },
        "op": {
          "type": "string"
        },
        "val": {
          "type": "number"
        }
      },
      "required": [
        "agg",
        "op",
        "val"
      ]
    },
    "isDeleted": {
      "type": "boolean"
    },
    "isDisabled": {
      "type": "boolean"
    },
    "perHostNotify": {
      "type": "boolean"
    },
    "note": {
      "type": "string"
    },
    "actions": {
      "type": "array"
    },
    "hostGroupId": {
      "type": "integer"
    },
    "timeoutInterval": {
      "type": "integer"
    }
  },
  "required": [
    "name",
    "metric",
    "triggerInterval",
    "typeId",
    "familyId",
    "isDeleted",
    "isDisabled",
    "perHostNotify"
  ]
}

=== jewelsjacobs/apiblueprints/boundary-alarm/includes/alarm-request.json
{
    "id": 100,
    "name": "Metric Threshold Alarm 1",
    "metric": "MEMU",
    "plugin": null,
    "triggerInterval": 60000,
    "typeId": 3,
    "familyId": 1,
    "triggerPredicate": {
        "agg": "avg",
        "op": "gt",
        "val": 9
    },
    "isDeleted": false,
    "isDisabled": false,
    "perHostNotify": true,
    "note": "",
    "actions": [],
    "hostGroupId": 9,
    "timeoutInterval": 14400000
}
